#!/usr/bin/env bash
# Build the wasm modules:
#   - packages/core/wasm: the Rust engine + the runtime for TS-authored machines, which
#     @dunky.dev/state-machine loads synchronously from the inlined bytes (wasm/bytes.js).
#   - sandbox/shared/rust/pkg: the sandbox machines written in Rust (palette, dialog).
#   - benchmark/rust/pkg: the benchmark machines written in Rust.
# Needs: rustup target wasm32-unknown-unknown, wasm-bindgen-cli matching the crate
# version (see Cargo.toml), and optionally wasm-opt (binaryen) for the size pass.
set -euo pipefail
cd "$(dirname "$0")/.."

# The features rustc enables by default for wasm32 (Rust >= 1.82); binaryen must accept them.
WASM_OPT_FLAGS=(-Oz --strip-debug --strip-producers
  --enable-bulk-memory --enable-bulk-memory-opt --enable-nontrapping-float-to-int
  --enable-sign-ext --enable-mutable-globals --enable-reference-types --enable-multivalue)

# build <crate> <lib name> <out dir> [cargo args...]
build() {
  local crate=$1 lib=$2 out=$3
  shift 3
  cargo build -p "$crate" --target wasm32-unknown-unknown --profile wasm "$@"
  # --target web: one ES module for browsers (init) and Node/Bun/tests (initSync).
  # --weak-refs: instances are freed by a FinalizationRegistry.
  # --reference-types: JS values cross as externrefs, so passing one costs no JS call.
  wasm-bindgen --target web --weak-refs --reference-types --out-dir "$out" "target/wasm32-unknown-unknown/wasm/$lib.wasm"
  if command -v wasm-opt >/dev/null 2>&1; then
    wasm-opt "${WASM_OPT_FLAGS[@]}" "$out/${lib}_bg.wasm" -o "$out/${lib}_bg.wasm"
  else
    echo "wasm-opt not found: skipping the size pass (brew install binaryen)" >&2
  fi
  local raw gz
  raw=$(wc -c < "$out/${lib}_bg.wasm" | tr -d ' ')
  gz=$(gzip -9c "$out/${lib}_bg.wasm" | wc -c | tr -d ' ')
  echo "$crate: ${raw} B raw, ${gz} B gzip"
}

build dunky-core-wasm dunky_core_wasm packages/core/wasm
# Inline the bytes so the package starts synchronously (no `await init()`).
{
  printf '// Generated by scripts/build-wasm.sh — the wasm of crates/core-wasm, base64.\n'
  printf 'export const WASM = "%s"\n' "$(base64 < packages/core/wasm/dunky_core_wasm_bg.wasm | tr -d '\n')"
} > packages/core/wasm/bytes.js
printf 'export declare const WASM: string\n' > packages/core/wasm/bytes.d.ts

build dunky-sandbox dunky_sandbox sandbox/shared/rust/pkg --features wasm
build dunky-benchmark dunky_benchmark benchmark/rust/pkg
